### ISSUE TITLE
README.md should link to CLI tool

### ISSUE THREAD

**Issue by SamB** [thlorenz/doctoc-web#6]
It'd be a good idea to mention/link to the commandline tool in this one's README, because I, at least, saw "get doctop app" and was like "okay, so they have a version that runs on smartphones?" before going on to click on "get source".

Or I guess you could reword the links in [views/root.jade](https://github.com/thlorenz/doctoc-web/blob/master/views/root.jade) ;-).

**Comment by thlorenz** [comment]
Agreed, could you provide a PR that does that?

**Comment by thlorenz** [comment]
Fixed
